name: untitled5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc: ^8.0.0
  flutter_lints: ^3.0.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5
  test: ^1.15.2
  bloc_test: ^9.1.7



flutter:
  uses-material-design: true
